### ISSUE TITLE
Remote Pagination with Remote Search/Filter functionality

### ISSUE THREAD

**Issue by wccsp** [mharris717/ember-cli-pagination#104]
NOTE: This is possibly a duplicate of #20 

First off, loving the add-on and up until now it has been working perfectly and saving me a ton of time! Thanks for all your work!

Ok, so now my problem: I am attempting to implement remote paging like so:
- normal remote paging functionality as described in the docs
- when the user uses the search input, the app requests a new page of filtered results

I can see that the model hook is being called, the remote request is being made, and the results are being returned, but the controller content is not updating with the filtered results.

my code is as follows:

/route.js
```
export default Ember.Route.extend(RemotePaginatedRouteMixin, {
    queryParams: {
        search: {
            refreshModel: true
        }
    },

    model: function(params) {
        return this.findPaged('admin/user', params);
    },

    actions: {
        searchApi: function() {
            this.refresh();
        }
    }
});
```

/controller.js
```
export default Ember.ArrayController.extend({
    queryParams: ['page', 'perPage', 'search'],

    page: 1,
    perPage: 10,

    pageBinding: 'content.page',
    perPageBinding: 'content.perPage',
    totalPagesBinding: 'content.totalPages'
});
```

Any ideas what I'm missing or a better approach to implementing the desired functionality?

**Comment by wccsp** [comment]
Mistake on my part. Everything is working perfectly!

**Comment by aranaravi** [comment]
Hi wccsp,
I am also trying to get the search in place can u guide me how to fix that, Thanks in advance.
