### ISSUE TITLE
Update addon to latest versions.

### ISSUE THREAD

**Issue by Robdel12** [mharris717/ember-cli-pagination#105]
I started digging in and upgrading but the tests are written in a way that makes it time sink to upgrade to the latest.

**Comment by mharris717** [comment]
I agree with you, I started it once but it was a huge PITA. 

What about them makes them particularly painful? Would love your insight.

**Comment by Robdel12** [comment]
Yes! I got to the point where I had to start sifting through each test file and figure out what was going on (due to the big qunit upgrade). 

I think the pain points are everything is a custom test function. I don't have a lot of project knowledge anymore so I'll have to dig in a little deeper to really tell you :P

**Comment by mharris717** [comment]
Understood. Honestly I should just budget some time and get this over with, because this is what's mentally blocking me from basically doing any new work on the project. 

I thought about writing a custom test function that worked in both styles, so I could upgrade incrementally, before I realized that was creating more work, not less.....

**Comment by Robdel12** [comment]
I'm about to push a branch on my fork that's working towards upgrading.

**Comment by Robdel12** [comment]
So, here's a pain point that I'm experiencing: The way the tests are written with the `createTests` function, I can't figure out a way to pass assert into it. That causes all the tests to break.

**Comment by Robdel12** [comment]
I have 78 failing tests :o

**Comment by mharris717** [comment]
I want to do this so bad, but our first customer goes live Monday at the job that pays me and I should probably focus on that. I might still give it a look this weekend :)

**Comment by mharris717** [comment]
WAAAAAAAAAAAT

https://travis-ci.org/mharris717/ember-cli-pagination/builds/65466645

**Comment by Robdel12** [comment]
Heyy!! That's awesome

**Comment by Robdel12** [comment]
So I'm going to slowly try and update this to 2.0.0 ready over the weekend. 
![screen shot 2015-06-13 at 1 23 33 pm](https://cloud.githubusercontent.com/assets/2072894/8145493/69df9ca2-11cf-11e5-939d-47d9c1599d6d.png)

**Comment by JKGisMe** [comment]
:+1: Was just coming to add the deprecation warnings for HTMLBars 

`{{#each thing in things}}`

is now

`{{#each things key="@guid" as |thing|}}`

Where the `key` property can be set to a unique property on the `thing` like `id` or just `@guid`.

**Comment by Robdel12** [comment]
Yea there's a lot of work to do, haha.

**Comment by mharris717** [comment]
@Robdel12 any interest in talking on skype in a bit?

**Comment by Robdel12** [comment]
Sorry, I stepped out for a couple hours. I got it down to 3 test fails. It has to do with the remote pagination query params

**Comment by Robdel12** [comment]
Just to give you a heads up.. I got really stuck on the query params stuff. That's the last thing standing to get it compat with 2.0

**Comment by mharris717** [comment]
@Robdel12 interesting. i know query params are kind of a mess with the upgrade

**Comment by mharris717** [comment]
@Robdel12 is your latest work pushed up to your upgrade-to-latest branch?

**Comment by mharris717** [comment]
@Robdel12 oooh, I did some bower install gymnastics that I don't understand and now I have the same 3 failures you do. Before I had 17.

**Comment by mharris717** [comment]
I don't know how to setup package.json and bower.json so i can do bower install without any manual intervention

**Comment by mharris717** [comment]
Ah, doing 1! when you select saves the resolution

http://madhatted.com/2015/5/14/ember-js-2-0-preview-with-canary

**Comment by Robdel12** [comment]
Haha! Yea my branch should be the latest :P Did you happen to make any headway?

**Comment by mharris717** [comment]
I could briefly make it pass locally, but not on travis. Now i have the problem where the tests freeze.

**Comment by mharris717** [comment]
beforeEach failed on basic meta: Attempting to register an unknown factory: `component:-link-to`

**Comment by broerse** [comment]
Is it perhaps an idea to use ember-cli-pagination version 0.6.6 for ember-cli < 1.13.1 and a new ember-cli-pagination version 1.0.0 for ember-cli 1.13.1 and up and break things?

**Comment by broerse** [comment]
Or call the breaking one ember-cli-pagination 1.13.0 to align it to Ember.

**Comment by broerse** [comment]
@Robdel12 It is time to update again ;-)  (to ember-cli 2.18)

PR's are welcome.

**Comment by Robdel12** [comment]
Ha! Sorry to cause notification churn. I was going through all of my oldest open issues
