### ISSUE TITLE
0-indexed page numbers

### ISSUE THREAD

**Issue by miguelcobain** [mharris717/ember-cli-pagination#111]
`InfiniteBase` does `this.addRecordsForPage(1)` on `init`: https://github.com/mharris717/ember-cli-pagination/blob/master/addon%2Finfinite%2Fpaged-infinite-array.js#L49

However, my backend has pages 0-indexed, so the first page is `0`.

Remote Route mixin has this solved by checking `this.get('startingPage')` at https://github.com/mharris717/ember-cli-pagination/blob/master/addon%2Fremote%2Froute-mixin.js#L21

Perhaps `InfiniteBase` should do a `this.addRecordsForPage(this.get('startingPage'))` as well, with `startingPage: 1` as default?

Right now what happens is that, the page 0 is fetched, but then sometime after that the page is set to `1` by the `addRecordsForPage(1)` call. That triggers a page change, and another fetch for page 1.

Maybe there are other places that need to be changed to allow a different starting page, but I think this should be overridable with a default of 1.

**Comment by broerse** [comment]
@miguelcobain Almost directly after you asked it is now solved in version v3.1.0 :smile:
