### ISSUE TITLE
IE8 Pages NAN

### ISSUE THREAD

**Issue by btecu** [mharris717/ember-cli-pagination#113]
Pagination works great. However, in IE8 I always get NAN and multiple warnings: ` no int for totalPages val is NaN`. I can log `content.meta.total_pages` and the value shows fine in IE8 too, so it's probably something internal to the addon.

Any idea?

**Comment by broerse** [comment]
On January 12, 2016 Microsoft stops Support for IE8 and will only support IE9 on Vista. Ember dropped support for IE8 in Ember 2.0. See: http://emberjs.com/blog/2015/04/20/ie8-support-update.html
I think ember-cli-pagination should support IE9+ until January 12, 2016 and switch to IE10+ support after that date.

**Comment by btecu** [comment]
I'm well aware of Microsoft's IE8 support. Ember 2.0 hasn't been released.

If I didn't had to support IE 8, I wouldn't be asking this question in the first place.

**Comment by broerse** [comment]
I don't think you should support IE8. I just tried some of my code to test your bug but they all fail because I use Pouch a lot. I will create a simple test project and will try to find your bug so you can use this module until January 12, 2016 ;-). I hope to get back to you today.

**Comment by broerse** [comment]
@btecu I build a test in IE8 emulation mode. See https://github.com/broerse/ember-cli-pagination-ie8
It runs without errors with `ember s`.

I still have some problems with the baseURL when I build it so I have not tested it with a real IE8. Do you get your errors in Emulation mode or in a real IE8?

**Comment by btecu** [comment]
I get the errors in a real IE8. In emulation mode it seems to work.

**Comment by broerse** [comment]
I can see the error now. Just tested ie9.js and:
https://github.com/broerse/ember-cli-pagination-ie8/commit/888e426b157389606b094c3a611c1f38ffadc504 It does not help yet :confused:

**Comment by broerse** [comment]
filteredContent is also not working in IE8 and this has nothing to do with this module. But perhaps it indicates that there is something wrong with binding. `pagedContent: pagedArray("filteredContent", {pageBinding: "page", perPageBinding: "perPage"}),`....

**Comment by broerse** [comment]
`http://localhost:4200/#/?page=2` Does show page 2 ???

**Comment by btecu** [comment]
Yes, `?page=2` works.

**Comment by broerse** [comment]
I can't find this bug. Perhaps don't use this module until January 12, 2016 ??

**Comment by broerse** [comment]
I just tried  code used in https://github.com/opsb/ember-cli-ie8-demo but can't get it to work. Perhaps it only fails on livereload,js?? Have to check later. Will push my breaking test to github.

**Comment by btecu** [comment]
I don't think it's an `ember-cli` issue.

**Comment by broerse** [comment]
It seem like a ES3 problem to me but can't find it. I like to help you but am running against my lack of skills in this area here.... I hope somebody with more knowledge in this field can take a look.

**Comment by jcope2013** [comment]
just an FYI I am seeing this on chrome 43 and ember 1.13.2 but i am not sure if related

**Comment by broerse** [comment]
Chrome 43 and ember 12.1 works. I have looked at this issue a long time and don't thinks it is related. Perhaps better report it as new issue. Mike has loads of time to handle them :smile:

**Comment by benkonrath** [comment]
I'm also interested in IE8 support. It would be nice to keep IE8 support in for Ember 1.x and drop it with versions that work with Ember 2.x.

On a somewhat unrelated note, does anybody know what the plans are for this projects. It seems that it needs some love to get up-to-date with the latest ember and ember-cli.

**Comment by btecu** [comment]
@benkonrath I ended up writing a component for pagination, since I only need server side pagination and it actually is very small and much cleaner.

Going forward with `JSONAPI` having support for pagination, this addon may decrease in usage. Probably sometime when Ember Data hits 2.1 or 2.2 and adds support for pagination.

**Comment by benkonrath** [comment]
@btecu I'm leaning towards writing a component for pagination as well. I usually prefer shared solutions for things like pagination but in this case it looks like my specific needs (server side pagination, IE8 support, Ember 1.13) aren't going to be met with this library. Thanks for chiming in.

**Comment by btecu** [comment]
No longer relevant.
