### ISSUE TITLE
install via bower

### ISSUE THREAD

**Issue by ramkumarb89** [mharris717/ember-cli-pagination#118]
I try to install the ember-cli-pagination via bower by using the following command. But it return an error as package ember-cli-pagination not found. Kindly help us.

command: bower install ember-cli-pagination

**Comment by Robdel12** [comment]
I don't think this package is on bower. In your Ember-CLI project do: `ember install ember-cli-pagination `

**Comment by broerse** [comment]
@Robdel12 This is not in the documentation. Perhaps we should add it. @mharris717 do we wait for the new version or can I write some PR for this.

**Comment by Robdel12** [comment]
@broerse Yea, I forgot this addon doesn't have any generators :p 

`npm install ember-cli-pagination --save-dev` works just fine in this case

**Comment by ramkumarb89** [comment]
@Robdel12  Thanks, I have used npm install ember-cli-pagination --save-dev command. which is installed and ember-cli-pagination in node_modules folder. But i cant able to import. Kindly give any idea.

**Comment by broerse** [comment]
@ramkumarb89 You can import like this: https://github.com/broerse/ember-cli-blog/blob/master/app/controllers/posts.js

**Comment by ramkumarb89** [comment]
@broerse Thank you

**Comment by broerse** [comment]
?? does your package.json contain  `"ember-cli-pagination": "^0.6.6",`

**Comment by ramkumarb89** [comment]
@broerse  yes

**Comment by broerse** [comment]
@ramkumarb89 Strange. If you try https://github.com/broerse/ember-cli-blog/ and it can't still load this module perhaps there is something wrong with your npm cache. You can test the ember-cli-blog without installing CouchDB.

**Comment by mharris717** [comment]
@broerse this is good to go with your README changes, right?

**Comment by broerse** [comment]
@mharris717 Yes! Not sure this solves @ramkumarb89 problem. Keep this open?

**Comment by mharris717** [comment]
@ramkumarb89 can you please give 0.9.0 a try and let us know if you're still having a problem?

**Comment by mharris717** [comment]
I am going to be optimistic and close this issue. @ramkumarb89 please feel free to reopen if you are still having an issue. 

Thanks for taking the time to log the issue in the first place.
