### ISSUE TITLE
page-numbers open Dialer on mobile

### ISSUE THREAD

**Issue by meggers** [mharris717/ember-cli-pagination#120]
On Android (tested on 4.4.2), tapping one of the page-numbers opens the phone number dialer instead of switching pages. Perhaps there needs to be a preventDefault somewhere?

I haven't found where this action is actually getting handled yet, but I'll submit a PR if I can find it as this completely breaks mobile functionality.

Thanks!

**Comment by meggers** [comment]
I was able to fix the issue by adding `href="#"` to all `a` tags in `page-numbers.hbs`. It doesn't seem like this causes any new issues - I will submit a PR for it.

**Comment by meggers** [comment]
Ah. I see that this has already been changed on github, but not on npm. Can you please push the changes?

Thank you!

**Comment by mharris717** [comment]
Thanks for taking the time to log this issue. My apologies for taking so long to get back to you.

0.9.0 was just pushed, which is definitely compatible with Ember 1.13.8. We will be working on pushing a 0.6.7 that supports older Ember versions with fixes, but it doesn't exist yet.. Not sure what version of Ember you're on, but give it try and see if 0.9.0 works for you.

**Comment by mharris717** [comment]
Going to close this issue, since it seems like the specific problem has been solved, even if there might be a lingering "version issue." Please feel free to reopen if you feel I'm mistaken.

**Comment by meggers** [comment]
Yep, the problem was solved with 0.9.0. Thanks!
