### ISSUE TITLE
0-index page

### ISSUE THREAD

**Issue by cedricziel** [mharris717/ember-cli-pagination#126]
Most APIs i know start paging 0 indexed - the pagination starts at 1.

Is there a non harmful way to override the starting index?

**Comment by mharris717** [comment]
I'm labeling this issue as low priority, only cause I have such a backlog that I need to triage aggressively. I hope to get back to it. 

Thank you for taking the time to contribute :)

**Comment by brentdanley** [comment]
Any progress on this? Did you figure out a solution, @cedricziel? I'm hitting three Drupal Views APIs, all with zero-indexed pages.

**Comment by broerse** [comment]
@brentdanley I don't use this module with a backend but in your template I think you want to show pape 1 for the first page. So if we keep the first page at 1 you can always subtract 1 in findPaged after `mainOps` is set depending on some flag. See https://github.com/mharris717/ember-cli-pagination#passing-other-params-to-findpaged 

I can try to create a branch with this option if you can test it.

**Comment by broerse** [comment]
Or it is more complex and we have to change something in https://github.com/mharris717/ember-cli-pagination/blob/master/addon/remote/mapping.js ??

**Comment by broerse** [comment]
@brentdanley Is there some open Drupal Views API I can use to test against?

**Comment by brentdanley** [comment]
@broerse Thank you for your responses. 

http://3blmedia.com/rest/report-announcement/latest-reports

**Comment by cedricziel** [comment]
@brentdanley it's been 2 years and we since then pivoted away from this module and ember as a framework. Good luck.

**Comment by brentdanley** [comment]
@cedricziel That's extreme. Do I need to tell my boss we can't use Ember because this addon won't allow zero-index page APIs? #kidding 

Will pour over the code today and try to find a solution. Any luck, @broerse?

**Comment by brentdanley** [comment]
There's also this issue: https://github.com/mharris717/ember-cli-pagination/issues/111

**Comment by cedricziel** [comment]
Hehe, no, no. This module was of course not the reason :)

**Comment by broerse** [comment]
@brentdanley I was trying [ember-drupal-waterwheel](https://github.com/acquia/ember-drupal-waterwheel) with your backend without pagination but do not have a working version yet. Is is easy for you to create a new ember-cli project with loads your data and displays it in a template? If not I was also looking at https://github.com/mharris717/ember-cli-pagination/blob/master/server/mocks/todos.js#L54 because perhaps I can use the mock to test 0 indexed response.

**Comment by brentdanley** [comment]
@broerse I could spin up a new Ember project with a route, model, adapter, serializer, and template, and put it somewhere that would be accessible for you, but it might be easier to user the mock TODO. Thank you so much for looking at this. I'm surprised, given the number of APIs that have zero-indexed pages, that this was downgraded and hasn't had any comment activity for two years. What is everybody else doing, I wonder?

**Comment by broerse** [comment]
@brentdanley I will try to fix this via the mock. @mharris717 does not have much time the last 2 years and we use this module everywhere in the Local scenario with [ember-pouch](https://github.com/pouchdb-community/ember-pouch) so I never looked much at the remote scenario. I will try to fix this anyway.

**Comment by brentdanley** [comment]
@broerse Thank you. That would be SUPER terrific! A page index flag would be perfect, so for each route I could indicate whether the API is zero- or one-based.

**Comment by brentdanley** [comment]
@broerse Modified a line in page-mixin.js and got it working for 0-index page APIs. However, this is not a proposed fix, because it breaks 1-indexed page APIs and is, therefore, neither backwards compatible nor flexible.

https://github.com/mharris717/ember-cli-pagination/blob/353b630fc2e485967e49489875af60b5866907f2/addon/page-mixin.js#L5

**Comment by broerse** [comment]
>  I think you want to show page 1 for the first page.

So the subtract has to be just before fetching the data from the backend. I will work on this this weekend. Or you can fix this today ;-)

**Comment by broerse** [comment]
@brentdanley My first working test: https://github.com/broerse/ember-cli-pagination/tree/0-based

Can you test if this works for your scenario? I will work on passing the flag. What is a logical name for this flag? Starting a param with `0` like `0_based`. Perhaps `remoteBasedIndex` 0  or 1 ?

**Comment by broerse** [comment]
Just also added `content: this.findPaged('todo',params,{zeroBasedIndex: true})`

**Comment by broerse** [comment]
@brentdanley Does is work for you and can I merge it?

**Comment by broerse** [comment]
@brentdanley tested some more and merged it in Master. Will update the readme later.

**Comment by broerse** [comment]
@cedricziel @brentdanley v3.1.0 enables you to access a zero based index remote API.

**Comment by cedricziel** [comment]
Alright, thx a bunch! :)
