### ISSUE TITLE
Compatibility with ember 1.13.8

### ISSUE THREAD

**Issue by mattcroberts** [mharris717/ember-cli-pagination#130]
Hi,

I've just upgraded my project from ember 0.2.5 to 1.13.8, I'm using the remote api and I'm not getting warnings in the console (see below). Are there any plans to upgrade this project to the latest ember? I've seen that @broerse has a branch which is up to date, could this be merged in?

```
no int for totalPages val is undefined
no int for currentPage val is NaN
```

**Comment by broerse** [comment]
I think Mike will merge today as 1.0.0.beta1

Also try changing to Ember 1.13.8 in your ember-cli 1.13.8. There are some bugs in Ember 1.13.7

**Comment by mattcroberts** [comment]
Thanks for the info about the upcoming beta and yes, the upgrading to ember 1.13.8 fixed my problems

**Comment by broerse** [comment]
It Live now.

**Comment by Robdel12** [comment]
Not yet, it has to be published to NPM first.

**Comment by broerse** [comment]
I can't have version 1.0.0.beta1 for Travis.....;-( . 3 dots... It will be fixed today.

**Comment by mharris717** [comment]
Released 0.9.0!

I made it 0.9.0 for now since Travis was complaining, figured not worth spending time on figuring it out

**Comment by mharris717** [comment]
Closing since I think this should be good now in 0.9.0. Feel free to reopen if I'm wrong, I just need to be aggressive in closing stuff to start cleaning up the backlog I created :)

Thanks @mattcroberts for logging the issue in the first place!

**Comment by Robdel12** [comment]
Woop! :D
