### ISSUE TITLE
Unable to install version 1.0.0 to suport ember-cli 1.13

### ISSUE THREAD

**Issue by ggrillone** [mharris717/ember-cli-pagination#132]
When installing it using the command provided in the docs: `ember install ember-cli-pagination` it is installing version `0.9.0`. So I tried to explicitly set it to `1.0.0` and I keep receiving the following error: `npm ERR! version not found: ember-cli-pagination@1.0.0`

**Comment by ggrillone** [comment]
Closing, found my answer here: https://github.com/mharris717/ember-cli-pagination/issues/130

**Comment by broerse** [comment]
@ggrillone I wrote 1.0.0 in the readme. Do we need to change this back to 0.9.0 ?? Or wait for the 1.0.0 release and do nothing??

**Comment by ggrillone** [comment]
I would say update the readme to say that `0.9.0` is the current latest version until `1.0.0` is released, because right now it seems misleading.
