### ISSUE TITLE
Page Numbers component actions not bubbling up

### ISSUE THREAD

**Issue by copasetickid** [mharris717/ember-cli-pagination#140]
I'm trying to bubble up the `pageClicked` action to the route in which up I'm using this addon. For some reason the event doesn't seem to bubble up back to my route after I defined it there.  Could it be it's not bubbling up because this component is also rendered from within another component?  Not sure what I'm missing so any tips will be appreciated.

**Comment by broerse** [comment]
Actions on Components don't bubble. You need to do this yourself. See:

https://github.com/broerse/ember-cli-blog/commit/f47854571e27c11e5d687927f156ff83bec7f137

**Comment by copasetickid** [comment]
Ok then can you explain to me what this line is doing then https://github.com/mharris717/ember-cli-pagination/blob/master/app/components/page-numbers.js#L78

because from understanding of action dispatch from a component will bubble back up based this from the ember guides?   If my wrong, its it possible to have multiples actions on an element as I don't want to override the original `pageClicked` method or should I follow you implementation where you defined the action on the component in which you call the `page-numbers` component from?

**Comment by broerse** [comment]
L78 Sends an action to a label called 'action'. See:

https://github.com/broerse/ember-cli-blog/blob/f47854571e27c11e5d687927f156ff83bec7f137/app/templates/components/blog-posts.hbs#L20

You don't override the original. You can rename `pageClicked' in my example to anything.

**Comment by broerse** [comment]
You can have multiple actions but ember-cli-pagination only defined 'action'

**Comment by copasetickid** [comment]
Ok thank you for explaining, I see where I got confused now with the actions within the my components and the add-on's.
