### ISSUE TITLE
Ember 2.0 deprecates ArrayController

### ISSUE THREAD

**Issue by chrsvl** [mharris717/ember-cli-pagination#141]
Hi there,

I updated my ember version to 2.0 and noticed that ArrayControllers are being deprecated. Will ember-cli-pagination work with regular Controllers?
Thanks in advance!

**Comment by benoittgt** [comment]
+1

**Comment by broerse** [comment]
Yes it will. Just use Components and it works.

https://github.com/broerse/ember-cli-blog/blob/master/app/templates/posts.hbs
https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-posts.js

**Comment by chrsvl** [comment]
Thank you!

**Comment by acorncom** [comment]
@chrsvl Should we close this issue?

**Comment by broerse** [comment]
@acorncom Yes help Mike close issues! :+1:

**Comment by DylanLukes** [comment]
The example doesn't necessarily work for remote pagination. Not sure this should be closed just yet...

**Comment by chrsvl** [comment]
Yes close it ;)
