### ISSUE TITLE
no currentPage for page-numbers - Remote Paginated API

### ISSUE THREAD

**Issue by cadab** [mharris717/ember-cli-pagination#151]
Hi,

I'm trying to get this add on working with my ember app.

I have an api which returns:

    {"Subscriptions":[
     {"Hostname":"PPE123","id":123,"Clients":[456]}],
     "meta":{"total_pages":15,"page":9,"perPage":1}
    }

Not sure if i need all them values returned? I think I only need total_pages?

My route looks like this:

    import Ember from "ember";
    import RouteMixin from 'ember-cli-pagination/remote/route-mixin';

    export default Ember.Route.extend(RouteMixin, {
      queryParams: {
        search: {
          refreshModel: true
        }
      }, 
      perPage: 25,    
       model: function(params) {	
		     return this.findPaged('subscription', params);		
       },
    });

And my controller:

    import Ember from "ember";
    export default Ember.Controller.extend({
	    needs: ['application'],
      queryParams: ['search', "page", "perPage"],
      search: "", 
  
      pageBinding: "model.meta.current_page",
      perPageBinding: "model.meta.per_page",
      totalPagesBinding: "model.meta.total_pages",
  
      page: 1,
      perPage: 10  
    });

When loading the page i get the following warnings in the console:

    no currentPage for page-numbers
    validate.js:12 no totalPages for page-numbers
    validate.js:12 no int for currentPage val is undefined
    validate.js:12 no int for totalPages val is undefined
    validate.js:12 no int for currentPage val is NaN
    validate.js:12 no int for totalPages val is NaN
    5validate.js:12 no int for totalPages val is NaN
    4validate.js:12 no int for totalPages val is NaN

Ive tried different variations of the bindings in the controller, with/without model/metric etc, but i always get the above warnings. Not sure where i'm going wrong?

Using version 1.13.7 of Ember.

Thanks,
James.

**Comment by jcope2013** [comment]
try moving the meta into a seperate object outside the subscriptions object and change page to current_page and perPage to per_page

``` "meta":{"total_pages":15,"current_page":9,"per_page":1}, "Subscriptions":[{"Hostname":"PPE123","id":123,"Clients":[456]}] ```

**Comment by cadab** [comment]
I've upgraded to Ember: 1.13.10, EmberData: 1.13.15, its made no difference.

The meta object is already separate to the subscriptions objects.

Ive tried switching the variable names like you suggested, but no difference i'm afraid.

Any other ideas?

James.

**Comment by jcope2013** [comment]
try

```
 pageBinding: "content.page",
  perPageBinding: "content.perPage",
  totalPagesBinding: "content.totalPages",
```

instead of

```
  pageBinding: "model.meta.current_page",
  perPageBinding: "model.meta.per_page",
  totalPagesBinding: "model.meta.total_pages",
```

**Comment by broerse** [comment]
Thanks @jcope2013

@cadab  Or try something like this:

https://github.com/broerse/ember-cli-blog/blob/master/app/templates/posts.hbs

https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-posts.js

Nothing to do with pagination. Your `needs: ['application'],` can be `application = Ember.inject.controller(),`

**Comment by cadab** [comment]
@jcope2013 unfortunately making them binding changes has no effect.

Not sure where i'm going wrong from the docs about remote paginated api.

**Comment by cadab** [comment]
So I gave up, and i'm just using the local store example and loading all of the data at once from the api.
