### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by dennismende** [mharris717/ember-cli-pagination#174]
Hi,

I only want to know what the status of this project is?

**Comment by mharris717** [comment]
Status is I've been meaning to find the time to keep up to date for months but so far it hasn't really happened

**Comment by Deovandski** [comment]
For someone who just found out about this project, the tip of my hat to you and the contributors for how handy it is!

**Comment by nadavshatz** [comment]
👍

**Comment by rizkytahara** [comment]
:+1:

**Comment by broerse** [comment]
@dennismende Removed the binding deprecation in version 3.0.1
