### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated.

### ISSUE THREAD

**Issue by broerse** [mharris717/ember-cli-pagination#178]
New deprecation for ember-cli. Seen in version 2.6.2

**Comment by aafaq-hassan-confiz** [comment]
Has this been fixed with issue 179?

**Comment by broerse** [comment]
Yes

**Comment by mharris717** [comment]
@broerse I gave you commit access. Sorry, I've sucked at maintaining this for a while

**Comment by broerse** [comment]
Hi Mike,

No problem. I know how life works ;-)
I will try to create the new version tonight. You will have to push it to
NPM when I am ready.

- Martin

**Comment by broerse** [comment]
Hi Mike,

https://github.com/mharris717/ember-cli-pagination/releases

Please push 2.2.2 to NPM

- Martin

**Comment by broerse** [comment]
Please publish 2.2.2 to npm.

**Comment by mharris717** [comment]
Will do this morning

On Thursday, June 30, 2016, Martin Broerse <notifications@github.com> wrote:

> Please publish 2.2.2 to npm.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mharris717/ember-cli-pagination/issues/178#issuecomment-229564178>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAD7KHPEXNC55hA407Yo188nmTV6831Fks5qQ1aXgaJpZM4I-k9N>
> .
>


-- 
Mike Harris
mharris717@gmail.com
(201)650-5579

**Comment by mharris717** [comment]
Done

**Comment by broerse** [comment]
Thanks!

**Comment by mharris717** [comment]
I'll make you a collaborator on npm. what's your name? @broerse

**Comment by broerse** [comment]
My npm name is `martinic`
