### ISSUE TITLE
DEPRECATION: `Ember.Binding` is deprecated. ?

### ISSUE THREAD

**Issue by rizkytahara** [mharris717/ember-cli-pagination#186]
I'm using:

```
$ ember -v
ember-cli: 2.7.0
node: 4.4.7
os: linux x64
```

using `remote-pagination` and got:

```
DEPRECATION: `Ember.Binding` is deprecated. Consider using an `alias` computed property instead. [deprecation id: ember-metal.binding] See http://emberjs.com/deprecations/v2.x#toc_ember-binding for more details.
```

any solutions?

**Comment by broerse** [comment]
I hope to upgrade to ember-cli 2.7.0 in two weeks. PR's that address this issue before that are welcome.

**Comment by jme783** [comment]
+1

**Comment by FrankSt** [comment]
+1

**Comment by jme783** [comment]
Any progress on getting this fixed?

**Comment by SaladFork** [comment]
I gave this a shot but got lost in the weeds. It's unfortunately not as straightforward as just following [the deprecation guide](http://emberjs.com/deprecations/v2.x#toc_ember-binding).

A few of the difficulties:
  * Just trying to run the tests on `master` without making any changes nondeterministically sometimes results in failing tests ("double start"). I can't figure it out but it seems there's some sort of race condition.
  * Some of the code introspects hashes to check for `/Binding$/` properties. This wasn't too difficult to address but is non-trivial and I'm not sure I got it fully working:
```js
// before
var getVal = function(key,val) {
  if (key.match(/Binding$/)) {
    return "parent."+val;
  }
  else {
    return val;
  }
};
for (var key in ops) {
  pagedOps[key] = getVal(key,ops[key]);
}
var paged = PagedArray.extend({
  contentBinding: "parent."+contentProperty
}).create(pagedOps);

// after (trying not to change too much about the code)
for (var key in ops) {
  var val = ops[key];

  if (key.match(/Binding$/)) {
    var keyWithoutBinding = key.substr(0, key.lastIndexOf("Binding"));
    pagedOps[keyWithoutBinding] = Ember.computed.alias(`parent.${val}`);
  } else {
    pagedOps[key] = val;
  }
}
var paged = PagedArray.extend({
  content: Ember.computed.alias(`parent.${contentProperty}`)
}).create(pagedOps);
```
  * Certain [code samples](https://github.com/mharris717/ember-cli-pagination/blob/6c31ae/doc/scenarios/remote-paginated-api.md#remote-paginated-api) and tests use the `/Binding$/` approach to set default values which make it harder to simply swap it out for `Ember.computed.alias`, as per:
```js
pageBinding: "content.page",
perPageBinding: "content.perPage",
totalPagesBinding: "content.totalPages",

page: 1,
perPage: 10
```

**Comment by broerse** [comment]
@SaladFork Thanks! Will start this weekend with the upgrade.

**Comment by SaladFork** [comment]
@broerse just edited my comment to mention my WIP branch, in case it helps save you some time :)

**Comment by broerse** [comment]
@SaladFork Started with upgrade first on https://github.com/broerse/ember-cli-pagination/tree/2.7.0 but failed. Will try to find error on https://github.com/broerse/ember-cli-pagination/blob/2.7.0/tests/unit/lib/remote/paged-remote-array-test.js#L105

**Comment by broerse** [comment]
@SaladFork I don't seem to get this fixed on my own. I will call in some help and will fix this. Just wait a little longer ;-(

**Comment by IntellectProductions** [comment]
+1  Any updates on this?

**Comment by SaladFork** [comment]
For anyone waiting on the fix, you can silence the deprecations for now by using [`ember-cli-deprecation-workflow`](https://github.com/mixonic/ember-cli-deprecation-workflow) and a config similar to:
```js
window.deprecationWorkflow = window.deprecationWorkflow || {};
window.deprecationWorkflow.config = {
  workflow: [
    // Deprecation caused by ember-cli-pagination, remove once fixed upstream
    { handler: 'silence', matchId: 'ember-metal.binding' }
  ]
};
```

**Comment by IntellectProductions** [comment]
Well in my current version I am using, this is not a deprecation.. I am getting this:

> Uncaught TypeError: (intermediate value).property is not a function

This is due to the paged-remote-array.js file:

`page: 1,
    paramMapping: (function () {
      return {};
    }).property(''),`

You now use `Ember.computed()` I believe.. I have been using `.property()` in other places and get the same error. I had to switch over to `Ember.computed()`

**Comment by jme783** [comment]
Any updates on this?

**Comment by broerse** [comment]
@jme783 We hope to be almost there. We need to solve some things. See first test:

https://github.com/broerse/ember-cli-blog/tree/bindless

**Comment by rizkytahara** [comment]
btw, this deprecation also occur when I'm using `ember-cli 2.8.0` :

```
DEPRECATION: `Enumerable#contains` is deprecated, use `Enumerable#includes` instead. [deprecation id: ember-runtime.enumerable-contains]
```

**Comment by byterussian** [comment]
Ember 2.9.0, same situation.

**Comment by denniss17** [comment]
Any progress?

**Comment by broerse** [comment]
@denniss17 I can't find a way to get query params working. I like to fix this. Mike is working hard on non Ember things so we will have to find someone that can help fix the query params.

**Comment by denniss17** [comment]
Any suggestions on how we could help?

**Comment by broerse** [comment]
@denniss17 https://github.com/mharris717/ember-cli-pagination/tree/2.7.0 passes the test but when I use it in  https://github.com/broerse/ember-cli-blog it fails on query params. It seems we are almost there. If you can get ember-cli-blog to work with https://github.com/mharris717/ember-cli-pagination/tree/2.7.0 I think we fixed it. It will be something simple Mike and I keep overlooking. (I hope). Also checkout https://github.com/mharris717/ember-cli-pagination/pull/192

**Comment by kronstadt1988** [comment]
Hopefully Santa Claus will create a PR for this deprecations :D

**Comment by broerse** [comment]
@kronstadt1988 @chrisccerami fixed the remote part so we are not completely the yet. But we released a working version in Beta https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.0.0-beta.1

**Comment by broerse** [comment]
@denniss17 We still need to fix the `pagedArray` see: https://github.com/mharris717/ember-cli-pagination/pull/199 Any help is welcome.

**Comment by broerse** [comment]
@jme783  We released a half working version. https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.0.0-beta.1 We still need to fix the pagedArray see: #199 Will keep you updated.

**Comment by jme783** [comment]
Hey @broerse ,

Really appreciate the ping. I know this is entirely an open-source repo, and I am very thankful for you maintainers! I'm eager to try it out, but as our ember app is currently in prod, I can't take too much of a gamble on a branch that's not ready for prime-time.

I look forward to when this gets wrapped up and merged back into `master`! 

Thanks again

**Comment by kronstadt1988** [comment]
Thanks. Amazing Work.

**Comment by broerse** [comment]
@balupton Fixed it all !!! 

https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.0.0
