### ISSUE TITLE
ember cli pagination not working for remote paginated data

### ISSUE THREAD

**Issue by VelDeveloper** [mharris717/ember-cli-pagination#193]
Hi i am trying to implement  a pagination in my application but i am unable to achieve that probably because of serialization of json.

Created following [stackoverflow](http://stackoverflow.com/questions/39857605/ember-cli-pagination-not-working) question to resolve the issue but no luck not getting any response.

Could you please guide me to resolve this issue. Since i am new to ember i don't know how to create a serializer for the JSON data.Any hint should be appreciable.

**Comment by stephencarr** [comment]
Looks like the Readme is out of date, take a look through the dummy app and you should be able to see how they set up a route, controller, and template to do remote: https://github.com/mharris717/ember-cli-pagination/tree/master/tests/dummy
