### ISSUE TITLE
Formatting/Limit pagination items.

### ISSUE THREAD

**Issue by dunice-igort** [mharris717/ember-cli-pagination#196]
Hi team,
I like your lib, thanks for documentation, pretty human readable:) 

I've sorted out how to configure items per page and current page number. But I still can't configure paging items length. Let me explain I need, that would be limit items for pagination (something like 1 ... 3 4 5 ... 16).

My requerements to have 5 items (for mobile only, because they not fit for parent div block). And I tried total_pages and all other fields realtated to that. Actually I've tried  almost all option keys:) But unfortunatly no results..

Could you please assist is it possible to implement by means of ember-cli-pagination?

Thanks once again for your lib.

**Comment by broerse** [comment]
Perhaps: `{{page-numbers content=content totalPages=5 showFL=true}}`

**Comment by broerse** [comment]
I see `numPagesToShow` is not in the doc?

**Comment by dunice-igort** [comment]
Oh, thank you very much, it works. But  the documentation doesn't contain numPagesToShow

**Comment by broerse** [comment]
If you have time to write a PR for the readme I will commit it ;-)

**Comment by broerse** [comment]
See https://github.com/mharris717/ember-cli-pagination/issues/197
