### ISSUE TITLE
Any working example for remote pagination?

### ISSUE THREAD

**Issue by meliborn** [mharris717/ember-cli-pagination#198]
Example from docs doesn't work in Ember 2+. ArrayController has been removed.

**Comment by stephencarr** [comment]
Not working for me either

```Could not find module `ember-cli-pagination/remote/route-mixin````

**Comment by broerse** [comment]
The [dummy app](https://github.com/mharris717/ember-cli-pagination/blob/master/tests/dummy/app/controllers/todos/remote.js) is working. We deprecated ArrayController long ago. We only need to change this in the readme. I am trying to fix the Ember Bindings depreciation and release v3.0.0

Perhaps we should rework the Readme.

**Comment by stephencarr** [comment]
Looking at the dummy app is the way to go. There are some scenario docs too which I didn't notice before. 👍

**Comment by greenmindPDX** [comment]
Used Kaminari on the Rails side. I didn't need a defined controller. All the business ended up being in the route.

My route: 
```
export default Ember.Route.extend(RouteMixin, {
  model: function(params) {
    params.paramMapping = { total_pages: "total-pages" };
    params.postId = this.paramsFor('post')['post_id'];
    return this.findPaged('comments', params);
  }
});
```
My template:
{{page-numbers content=comments}}

**Comment by lancedikson** [comment]
Using `Ember.computed.oneWay` instead of `.alias` works. Has to be fixed, I guess.

**Comment by mcand** [comment]
What is the content in pagedContent ? I'm having problem to use the addon..

```
import Ember from 'ember';
import pagedArray from 'ember-cli-pagination/computed/paged-array';

export default Ember.Controller.extend({
  queryParams: ["page","perPage"],
  page: 1,

  pagedContent: pagedArray("content", {pageBinding: "page"})
});
```

**Comment by broerse** [comment]
@mcand Try with version 3.0.1

```
pagedContent: pagedArray('content', {
    page: Ember.computed.alias("parent.page"),
    perPage: Ember.computed.alias("parent.perPage")
  }),
```
See also the updated docs.

**Comment by broerse** [comment]
@mcand `content` is the model but it can be any model. See: https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-posts.js#L29
