### ISSUE TITLE
Use link-to helper to generate pagination links

### ISSUE THREAD

**Issue by stephencarr** [mharris717/ember-cli-pagination#200]
Using the link-to helper seems to be the correct way to link with query parameters pushed to the URL. At the moment when I page through a model-view I simply get `http://example.com/model` no matter what page I am on. Using link-to should give us `http://example.com/model?page=2`.

```
<a href="#" {{action "pageClicked" item.page}}>{{item.page}}</a>
```
becomes...
```
{{#link-to "model" (query-params page= item.page}}{{item.page}}{{/link-to}}
```

I am not sure if the component already has a model scoped to it, but if not it should be possible to pass it in. I recognize that there may be a lot more to this than I am aware of, but it seems to be the correct thing to do.

https://guides.emberjs.com/v2.3.0/routing/query-params/#toc_link-to-helper

**Comment by broerse** [comment]
If you put your query pamrameters on the controller like this: https://github.com/broerse/ember-cli-blog/blob/master/app/controllers/posts.js it works. See https://bloggr.exmer.com
