### ISSUE TITLE
How to reset infinite pagination pagedContent to clear the old results?

### ISSUE THREAD

**Issue by marceloandrader** [mharris717/ember-cli-pagination#201]
Hey,

We've been using this excellent library for a while with remote pagination and it's working really well, thank you for making it.

Recently we received a feature request about infinite scroll, which we implemented really easily with this addon, but it collides with another feature we have on our tables, is that when you filter something, the request to the server goes correctly and I get the filtered result, but the pagedContent never changes, I'm not sure how to reset the pagedContent to clear the previous all/content properties.

I tried with `this.get('pagedContent').init() `but doesn't work.

Not sure what else can I do.

Thanks in advance

**Comment by balinterdi** [comment]
I'm not very familiar with ember-cli-pagination but if pagedContent behaves like an array, `this.get('pagedContent').clear()` should work.

**Comment by marceloandrader** [comment]
@balinterdi thank you that worked to clear the contents of the pagedContent, but there is a bug on infinite content that doesn't update the data when the model is refreshed. I'll create a PR for that.

**Comment by broerse** [comment]
Fixed in v3.0.0-beta.2
