### ISSUE TITLE
Not possible to extend `page-number` component

### ISSUE THREAD

**Issue by lancedikson** [mharris717/ember-cli-pagination#204]
Looks like there is no any possibility to extend the `page-numbers` component because it placed to `app/components` directory. If it was placed to `addon/components` directory, it would be possible to make `import PageNumbers from 'ember-cli-pagination/components/page-numbers'` and then extend it somehow. Am I right?

**Comment by broerse** [comment]
Fixed in v3.0.0-beta.2
