### ISSUE TITLE
Upgrade to ember-cli-babel@^6.0.0

### ISSUE THREAD

**Issue by Blackening999** [mharris717/ember-cli-pagination#224]
This addon is outdated with the recent Ember versions

```
ember-cli-pagination@3.0.2:
  version "3.0.2"
  resolved "https://registry.yarnpkg.com/ember-cli-pagination/-/ember-cli-pagination-3.0.2.tgz#9d51f2b6ad80b0b98729f0b18de8a2d02e4fc26b"
  dependencies:
    ember-cli-babel "^5.1.6"
    ember-cli-htmlbars "^1.1.1"
    ember-cli-version-checker "^1.1.5"
```

```
$> ember -v

ember-cli: 2.14.1
node: 8.2.1
os: darwin x64
```

**Comment by broerse** [comment]
Please make a PR for it. There is a problem with ember-try and Travis Trusty so perhaps do https://github.com/pouchdb-community/ember-pouch/commit/30c4928afca9e79fe2c2eff8d24e7ba973a5a4e5 until ember-try is fixed.

**Comment by broerse** [comment]
@Blackening999  It is now fixed thanks to @mixonic . See [3.1.1](https://github.com/mharris717/ember-cli-pagination/releases/tag/v3.1.1)
