### ISSUE TITLE
total_pages underscore vs dasherized

### ISSUE THREAD

**Issue by nolman** [mharris717/ember-cli-pagination#236]
Thanks for writing `ember-cli-pagination`. I have an issue with how a couple libraries are interacting and thought I would open an issue to start a discussion.

We are using JSONAPI powered by Ember data, ActiveModelSerializers AMS), and Ember CLI Pagination.

Our AMS gem is setup to dasherize all the keys which has worked very well with ember data and everything else thus far, but we are unable to get AMS to leave the total_pages key underscored. Would it be possible to allow for `total_pages` or `total-pages` or `totalPages` or at the very least the ability to configured the expected response? Apologies if this is already supported and I missed it.

**Comment by broerse** [comment]
Does the paramMapping not work in this case?

https://github.com/mharris717/ember-cli-pagination#using-other-names-for-pageperpagetotal_pages

**Comment by sdhull** [comment]
I was able to get `paramMapping` to work. Thank you! You can close this issue.
