### ISSUE TITLE
Not Able to Display Page Number

### ISSUE THREAD

**Issue by sonasingh46** [mharris717/ember-cli-pagination#239]
I am using following :  
``{{#each pagedContent as |account|}}
<p> {{account.name}}</p>
{{/each}}

{{page-numbers content=pagedContent}}``

If i do not write '{{page-numbers content=pagedContent}}' data shows up(of current page) but page number is not displayed.
If I write  '{{page-numbers content=pagedContent}}'  nothing is rendered ... shows some error in console.

**Comment by broerse** [comment]
This seems OK. Does your code look something like this?

https://github.com/broerse/ember-cli-blog/blob/master/app/components/blog-posts.js

**Comment by sonasingh46** [comment]
Thankyou for responding @broerse 
I found my problem and fixed.
Actually i generated my own template  page-numbers.hbs so as to customize it and then forgot to write there and then I was expecting the default page numbers to be displayed.
Sorry about this. 
Now everything is working fine and I am able to customize the template also. 
:)
