### ISSUE TITLE
Fix sendAction Deprecations

### ISSUE THREAD

**Issue by broerse** [mharris717/ember-cli-pagination#257]
Fix sendAction Deprecations https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-component-send-action

https://github.com/mharris717/ember-cli-pagination/blob/master/addon/components/page-numbers.js#L69

and

https://github.com/mharris717/ember-cli-pagination/blob/master/addon/components/page-numbers.js#L80

**Comment by rinoldsimon** [comment]
same deprecation warning in
`ember-cli` - `3.7.1`
`ember-cli-pagination` - `3.1.4`

**Comment by broerse** [comment]
Fixed by version 3.1.5
