### ISSUE TITLE
Handling an invalid page query param

### ISSUE THREAD

**Issue by mharris717** [mharris717/ember-cli-pagination#36]
I'm not sure what the proper behavior is in this scenario. 

ht @broerse

**Comment by broerse** [comment]
The page=666 bug is still in the current version I think. See: http://exmer.com/bloggrcouch/posts?page=10&query=test but it can be [my code](https://github.com/broerse/ember-cli-blog/blob/master/app/controllers/posts.js) also.

**Comment by broerse** [comment]
Perhaps open this issue again?
