### ISSUE TITLE
how to reload the model

### ISSUE THREAD

**Issue by matheusdavidson** [mharris717/ember-cli-pagination#57]
Hi there, this is not an issue, more like a question.
I have two more fields that goes to the server which are:
Order and Filter.

I would like to reload the model everytime user changes order or press enter on filter.
I was not able to use this.get('model').reload();
It is already working if i change the filter or order and after i change the page, params are sent ok, but i would like to reload when the user change any of this fields with an "observes".

How can it be done?

**Comment by danshapir** [comment]
Hey, I saw that you've added this to the source code, but haven't released a new version (0.6.7), so the code isn't available. Can you please release a new version?

**Comment by GesJeremie** [comment]
This issue just helped me, thanks for that :)
