### ISSUE TITLE
Show loading spinner while model is loading

### ISSUE THREAD

**Issue by matheusdavidson** [mharris717/ember-cli-pagination#64]
Hi,
before using your pagination, i use to have a loading var on my controllers set to false, whenever i changed the model i would set this loading to true and to false again on the promise return, success/fail method(i mean "save().then(success, fail)"), so i can show a loading spinner on the view(just in the table area) while model is loading.

Question is, how can i implement this with this pagination?
i thought something like this:
```js
var loading = false,
fetchContent: function() {
    this.set('loading', true);
    res.then(function(rows) {
        this.set('loading', false);
    }
}
```
then in my template:
```html
{{#if loading}}
<!-- Show loading -->
{{else}}
<!-- List entries -->
{{/if}}
```
I intend to use a reopen(paged-remote-array) on a mixing to add this implementation.
Thank you.

**Comment by blakecash** [comment]
:+1:  for @matheusdavidson implementation.

**Comment by mharris717** [comment]
Sorry for the epic delays in responding, my carrier pigeons keep getting lost. 

I like what you did, I'll give it a try.

**Comment by clawfire** [comment]
Just an :bulb: : why don't using the `*-loading.hbs` view instead of a custom loader. It's what ember already use when loading a model ... or it's what you did @blakecash with the `{{partial "loading"}}`  ?

**Comment by matheusdavidson** [comment]
The default loading only fires when there is a transition in the route, my implementation loads and reloads the model by an action in the controller without any transition.

```{{partial "loading"}}``` is the same view that i use for default and custom loading.

**Comment by mharris717** [comment]
Added. https://github.com/mharris717/ember-cli-pagination/pull/137

Sorry I took so long here. Life really got in the way for a while. Thanks for taking the time to contribute!
