### ISSUE TITLE
Observers on pageChanged function causing two network requests to be made

### ISSUE THREAD

**Issue by jcope2013** [mharris717/ember-cli-pagination#72]
right now it looks like this in paged-remote-array.js

```
pageChanged: function() {
   this.set("promise", this.fetchContent());
  }.observes("page", "perPage"),
```

a better solution would look like this 

```
pageChanged: function() {
    Ember.run.once(this, 'processPageChanged');
  }.observes("page", "perPage"),

 processPageChanged: function() {
   this.set("promise", this.fetchContent());
}
```

"This will ensure that any processing you need to do only happens once, and happens in the next run loop once all bindings are synchronized"

http://emberjs.com/guides/object-model/observers/

this still seems to be triggering two network requests though when I changed the code, sticking a debugger shows processPageChanged still getting triggered twice when I change the page, what would be a better way to observe query params binding so only one network request gets triggered?

**Comment by ashwani19** [comment]
Facing the same issue. when shall you going to fix this?

**Comment by mikeumus** [comment]
+1

**Comment by aleontiev** [comment]
+1 really loving this add-on except for this one issue

Here is my hacky fix, this prevents the 2nd request from going out:

```  
pageChanged: function() {
    var page = this.get('page');
    var lastPage = this.get('lastPage');
    if (lastPage != page) {
      this.set('lastPage', page);
      this.set("promise", this.fetchContent());
    }
  }.observes("page", "perPage"),
```

**Comment by mharris717** [comment]
Seems like this is biggest outstanding issue. I will take a crack at it first chance I get.

**Comment by jcope2013** [comment]
any update on this, @aleontiev thanks for the fix

**Comment by engwan** [comment]
+1, I'm also having a similar issue. But it only happens when I bind the page property to the queryParam.

I'm not setting refreshModel to true so I'm not sure what causes the double request

**Comment by irruputuncu** [comment]
I am also having this issue with the newest version and a remote paginated api. When I use query parameters and set them as alias as described in the docs it makes two requests. When I use oneWay instead of alias only one request is made but the query params do not work anymore.

**Comment by broerse** [comment]
@irruputuncu This seems to be a new issue. Not sure? Perhaps we should close this an create a new issue?

**Comment by irruputuncu** [comment]
You are right, this issue has similar symptoms but probably a different origin. I will open a new issue with some more details.

**Comment by broerse** [comment]
@irruputuncu Thanks. Will close this one.
