### ISSUE TITLE
no total_pages in meta response

### ISSUE THREAD

**Issue by mrmylanman** [mharris717/ember-cli-pagination#75]
Hello,

First, I must say that this library is pretty cool and is a big help in getting set up with some new Ember projects I'm working on.

Unfortunately, I am receiving some errors when trying to use a model with a DS.ActiveModelAdapter backend.

Just for reference here is some code:

```javascript
// adapters/application.js
import DS from 'ember-data';

export default DS.ActiveModelAdapter.extend({
  namespace: 'api',
  host: 'http://localhost:3000'
});
```

```javascript
// controllers/users.js
import Ember from 'ember';

export default Ember.ArrayController.extend({
  queryParams: ['page', 'perPage'],
  pageBinding: 'model.page',
  perPageBinding: 'model.perPage',
  totalPagesBinding: 'model.totalPages',
  page: 1,
  perPage: 20
});
```

```javascript
// /models/user.js
import DS from 'ember-data';

export default DS.Model.extend({
  lastName: DS.attr('string'),
  firstName: DS.attr('string'),
  email: DS.attr('string'),
  clockEvents: DS.hasMany('clock-event')
});
```

```javascript
// /routes/users.js
import Ember from 'ember';

import RouteMixin from 'ember-cli-pagination/remote/route-mixin';

export default Ember.Route.extend(RouteMixin, {
  perPage: 20,
  model: function(params) {
    params.paramMapping = {
      page: 'page',
      perPage: 'per_page',
      total_pages: 'Total-Pages'
    };
    return this.findPaged('user', params);
  }
});
```

In my users template I am able to iterate over the paged array of users and I set a paginator with:

```handlebars
{{page-numbers content=model
```

It is able to get the current page and show arrows, however the "next" arrow is grayed out (though I can still click on it). In the console I have a number of warnings:

```
ember.js:15373 no total_pages in meta response
ember.js:15373 Object {}
ember.js:15373 no totalPages for page-numbers
ember.js:15373 no int for totalPages val is undefined
ember.js:15373 no int for totalPages val is NaN
9ember.js:15373 no int for totalPages val is NaN
```

Here are some sample headers in the response from my API server:

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Methods:GET, POST, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin:http://localhost:4200
Access-Control-Expose-Headers:
Access-Control-Max-Age:1728000
Cache-Control:max-age=0, private, must-revalidate
Connection:Keep-Alive
Date:Mon, 12 Jan 2015 20:25:13 GMT
Etag:W/"653880d357c59f060b877659a7ea3213"
Next-Page:2
Offset:0
Page:1
Per-Page:20
Prev-Page:
Server:WEBrick/1.3.1 (Ruby/2.2.0/2014-12-25)
Total:149
Total-Pages:8
Vary:Origin
X-Request-Id:dfa3771e-dc5d-4496-8748-8f8c9b3fe5ee
X-Runtime:0.045344
```

Originally the pagination stuff had `X-` prefixes, but it didn't work so I tried removing the prefix to see if it would improve the situation but it doesn't seem to have.

The `params.paramsMapping` seems to have an affect for the perPage but I don't think it's working for the total_pages part.

If anyone can point me in the right direction or give me some advice I'd greatly appreciate it. I am still very new to Ember so I might be missing something obvious.

Thanks!

**Comment by mharris717** [comment]
I don't believe returning the meta info as headers will work at this time. A response with a meta tag in the body is expected. 

Example

```json
{"meta": {"total_pages": 10},
"users": [
  {id: 1, email: ""},
  ...
]}
```

What does the body of the response look like?

**Comment by mrmylanman** [comment]
Just before I saw your response I was browsing Ember's docs and came to the same conclusion you came to. I missed the section on their site about metadata, which actually lays it out pretty clearly...

I apologize I must have misunderstood what was necessary. Like I said, new to Ember! I am sure that is where the issue lies. Thanks for the response!

**Comment by mharris717** [comment]
No worries, glad I could help.

Returning pagination info in the headers is not uncommon, it's a use case we'd like to support at some point.

**Comment by mrmylanman** [comment]
Got around to working on it again, and sure enough that appears to have been the problem.

The biggest problem was Active Model Serializer didn't work on Rails-API for me and that was causing some additional confusion; this just got caught up in it.

When the `meta` tag is included in the JSON response (with the fields expected), all's well.

Thanks again!

**Comment by shanekoss** [comment]
@mylanconnolly - i'm hitting the same issue here with AMS - how did you get it to return total_pages and not total-pages?  Thanks!

**Comment by mylanconnolly** [comment]
@shanekoss

Unfortunately, I haven't used AMD (or Rails) in a while so I do not recall the specifics.

Sorry I couldn't help

**Comment by shanekoss** [comment]
Thanks for getting back to me.

**Comment by roschaefer** [comment]
@shanekoss I'm using Rails 5.0 with Active Model Serializers and `kaminari` for pagination on the backend side, as well as the ordinary `JSONAPIAdapter` on the frontend side. Changing `total_pages` to `total-pages` should work just as you see it in the first post of this thread. Here's some code for a model called `statistic/broadcast`:

```javascript
  model: function(params) {
    params.paramMapping = {
      total_pages: "total-pages"
    };
    return this.findPaged('statistic/broadcast', params);
}
```
