### ISSUE TITLE
Implement Remote Paginated API with findQuery

### ISSUE THREAD

**Issue by boazin** [mharris717/ember-cli-pagination#76]
Not a bug but assistance request:
I'm having trouble implementing 'Remote Paginated API' when using findQuery

The route:
```
export default Ember.Route.extend({
    model: function(params) {
      return this.store.findQuery('session', params.filters);
    }
});
```

How do I get the `findPaged` in here?

**Comment by mharris717** [comment]
Try this

```javascript
this.findPaged('session',params.filters)
```

**Comment by boazin** [comment]
I'm getting:
`Error while processing route: search-sessions Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined`

I think it is because I'm losing the perPage and page when using `params.filters` but if I pass params - the server won't know what to do with it...

**Comment by boazin** [comment]
I'm passing a qury string with `transitionToRoute` to this route

**Comment by mharris717** [comment]
You want to pass a hash to findPaged with the stuff in `params.filters` at the top level.

So if you have this:

```json
{page: 2, filters: {name: "Adam"}}
```

Turn it into this
```json
{page: 2, name: "Adam"}
```

Basically, if the params hash you pass to `findPaged` contains non-page keys, `findPaged` will pass those along to your API.

**Comment by boazin** [comment]
So basically what you are saying is that I need to split the query string and put it in the params structure...

**Comment by mharris717** [comment]
I don't think I understand what you're doing.

If you write up what you are doing in detail, I will take a look and try and help you out in the next day or so.

**Comment by boazin** [comment]
Thanks. 
The reason I had trouble is because transitionToRoute requires a string and not an object so I had to parse it and make a proper params object
