### ISSUE TITLE
Remote Paginated API doesn't work with latest ember-cli

### ISSUE THREAD

**Issue by codepreneur** [mharris717/ember-cli-pagination#79]
Every time I try to use it, I get:

```
File: fit2me-admin/routes/users.js
ENOENT, no such file or directory '/Users/johndoe/fit2me-admin/tmp/tree_merger-tmp_dest_dir-StzgqLlh.tmp/ember-cli-pagination/addon/remote/route-mixin.js'
Error: ENOENT, no such file or directory '/Users/johndoe/fit2me-admin/tmp/tree_merger-tmp_dest_dir-StzgqLlh.tmp/ember-cli-pagination/addon/remote/route-mixin.js'
    at Object.fs.statSync (fs.js:696:18)
    at addModule (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:84:46)
    at addModule (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:133:9)
    at /Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:59:7
    at $$$internal$$tryCatch (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/Users/johndoe/fit2me-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:442:13)
```

Even though the file definitely is there.

http://stackoverflow.com/questions/28027900/ember-cli-pagination-remote-paginated-api-doesnt-work-with-latest-ember-cli

And yes, I already tried:
```
rm -rf node_modules/
rm -rf bower_components/
npm cache clean
bower cache clean
npm install
bower install
```

and it didn't work :(

**Comment by mharris717** [comment]
Thanks for the issue, I'll check it out.

**Comment by mharris717** [comment]
Just published 0.6.4 upgraded to ember-cli 0.1.7 thanks to @tonycoco, hoping/assuming this fixes your problem. Please let me know if it doesn't / close the issue if it does. Sorry you had this crummy experience.

**Comment by funtusov** [comment]
After I upgraded I have this issue, also with the remote paginated API:

``Error while processing route: something.index Cannot read property 'QueryParamsForBackend' of undefined TypeError: Cannot read property 'QueryParamsForBackend' of undefined``

From the debugger it seemed that the export that contained QueryParamsForBackend was empty (just ``{}``)

```
EmberCLI: 0.1.9
Ember      : 1.11.0-beta.1+canary.f87c158f
Ember Data : 1.0.0-beta.15-canary
```

**Comment by mharris717** [comment]
Sigh. This is pretty annoying that this keeps happening. I'll check it out, thanks for the issue.

**Comment by funtusov** [comment]
Sure, let me know if I can help. Reverting to ``0.1.7`` fixes the issue, so I think that's one of the addon's related pull requests merged in ``0.1.8``

**Comment by mharris717** [comment]
New version of CLI didn't like the way I was doing a module export for some reason. Changed it and released 0.6.6, let me know.

**Comment by funtusov** [comment]
Works now, thanks! :+1:

**Comment by mharris717** [comment]
Excellent!

**Comment by jcope2013** [comment]
@mharris717 thanks! :thumbsup:

**Comment by broerse** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
