### ISSUE TITLE
working in a "Remote Paginated API" scenario without TotalPages

### ISSUE THREAD

**Issue by boazin** [mharris717/ember-cli-pagination#84]
It is more of a question/FR:

We are considering removing the TotalPages from the reply (to boost performance in large scale)

How will ember-cli-pagination behave in this case? is it supported?

Thanks

**Comment by mharris717** [comment]
It won't work, because it won't know, well, how many pages there are.

What about returning a fixed constant as total_pages, instead of calculating it? You could also set total_pages to a constant value client side after the data is returned.

**Comment by boazin** [comment]
So you are suggesting - to provide a "large enough number" - and when a user clicks "next page" he will just see an empty table... 

It would seem like a bug, no?

**Comment by mharris717** [comment]
I guess I don't understand your scenario.

I was guessing that the situation is you have theoretically thousands of pages, or at least more pages than the user would ever want to see, like a google search, and that calculating the actual number of pages would be computationally expensive for no benefit. So my solution to this hypothetical was to just return a big number. 

I can offer advice if you can specify your scenario in more detail.

**Comment by boazin** [comment]
You got it perfectly right... 
But sometimes the query will be "good" and will have let's say 40 results
In your suggestion - (let's say we have 10 results per page) - the big number will make ember-cli-pagination think there is a page 5 and 6 and so on... When the user will click "next" from 4 to 5 he will get an empty page - a case which the server supports but is much less nicer than "stopping"

**Comment by mharris717** [comment]
Are you asking for the ability to determine the number of pages "on the fly," meaning that when the lib receives an empty page, it is implied that the prev page was the last page and/or a page with a count less than the perPage value is the last page?

**Comment by mharris717** [comment]
It's actually more complex than that, because that assumes the user only clicks next page. The user could jump around in pages.

**Comment by boazin** [comment]
Yeah... That's why presenting 1..8 when there are actually 4 pages looks "buggy"

**Comment by mharris717** [comment]
Ok. What I'm hearing is that you need the component to accurately reflect the number of pages, but you don't want to return the total_pages in the response. That seems to be a contradiction.

I'm honestly not trying to be flip, just trying to make sure I understand the scenario.

**Comment by mharris717** [comment]
Your original question may have simply been asking what would happen if you did that and not asking for new functionality, and I dragged you down this conversation path. So the short answer is it won't work :)

**Comment by boazin** [comment]
I completely see your point... The short answer - I need to fake a number

Don't worry - I wanted to have a conversation (it's the only medium I can reach you :))
