### ISSUE TITLE
How to Update Pager?

### ISSUE THREAD

**Issue by gte451f** [mharris717/ember-cli-pagination#89]
When using the Remote Paginated API option, I have trouble updating the pager when I've added a new record to the found set.

Put another way, if I just added a record via something like Ember Data, how do I tell the Pager about the new record WITHOUT triggering a full XHR request?

I try adding the record to the store like this...

    store.push('document', store.normalize('document', data));

...and while the record shows up on my Ember inspector, the Pager won't show the record.

**Comment by knownasilya** [comment]
```js
page: 1,
perPage: 10,
pagedContent: pagedArray('model', { pageBinding: 'page', perPageBinding: 'perPage' }),

actions: {
  addModel: function () {
    var models = this.get('model');
    var model = this.store.createRecord('myModel', {
      fun: true,
      foo: 'bar'
    });

    model.save()
       // might not be necessary if you did get the models via store.find('myModel')
      .then(function () {
        models.addRecord(model);
      }, function (error) {
        console.error(error);
      });
  }
}
```

**Comment by gte451f** [comment]
I've tried this a few different ways but no joy.  

    // errors out that addRecord is undefined.
    models.addRecord()


    // this works fine on a regular model, but I get...
    // The result of a server query (on BADASSAPP@model:document:) is immutable.
    // pagedArray
    var models = this.get('model');
    var doc = {
        name: 'my name',
        size: 23
    };
    var model = this.store.createRecord('document', doc);
    models.pushObject(model);

I suspect the pagedArray being remote (in my case) prevents me from adding/remove records to/from it?

**Comment by gte451f** [comment]
Ok, here is a working example

    // add to models.content.addRecord instead
    var models = this.get('model');
    var doc = {
        name: 'my name',
        size: 23
    };
    var model = this.store.createRecord('document', doc);
    models.content.addRecord(model);

**Comment by knownasilya** [comment]
@gte451f which shouldn't be, since there should be a proxy @mharris717

**Comment by vasilakisfil** [comment]
Not working for me not matter what. Tried get('models.content').pushObject(model), get('models.content.content').pushObject(model), get('models.content').addRecord(model) and get('models.content.content').addRecord(model) all fail.

**Comment by vasilakisfil** [comment]
There should definitely be a way to push records to PagedRemoteArray :)

**Comment by williamweckl** [comment]
Did not work for me either. 

My code:

```javascript
      return adapter.ajax(url, 'POST', {
        email: email
      }).then(function(data) {
        var normalized = store.normalize(modelName, data.object);
        store.push(normalized); //works with this.store.findAll
      });
```
```javascript
model(params) {
    return this.findPaged('billing/delivery-file',params); //paginated not working push to store
    // return this.store.findAll('billing/delivery-file'); (this works)
  }
```

**Comment by williamweckl** [comment]
@vasilakisfil did you got any working solution?
