### ISSUE TITLE
Following install instructions yields Could not find module error 

### ISSUE THREAD

**Issue by gap** [mharris717/ember-cli-pagination#92]
I've installed using `npm install ember-cli-pagination --save-dev`.  When I add the line `import pagedArray from 'ember-cli-pagination/addon/computed/paged-array';` to a controller I get the error `Uncaught Error: Could not find module ember-cli-pagination/addon/computed/paged-array`.

The install instructions are minimalist and provide no guidance if they fail.  If I knew how to resolve the error I'd create a pull request.

**Comment by broerse** [comment]
It is in: `import pagedArray from 'ember-cli-pagination/computed/paged-array';`

**Comment by gap** [comment]
I get `Uncaught Error: Could not find module ember-cli-pagination/computed/paged-array `   I tried many permutations (which is how I posted the wrong one).

**Comment by broerse** [comment]
It works for me. If you install my example:
https://github.com/broerse/ember-cli-blog
that includes ember-cli-pagination do you get the error?

**Comment by gap** [comment]
Your example and everything else works now.  Oddd....
