### ISSUE TITLE
Prevent sending the perPage query param

### ISSUE THREAD

**Issue by ryanwood** [mharris717/ember-cli-pagination#96]
Using the remote pagination feature, I don't want to send the `perPage` queryParam. I've tried taking `perPage` out of the queryParams in the controller but it is still sent when switching pages. Am I missing a simple way to prevent that param from being sent in the remote request?

**Comment by ryanwood** [comment]
Just as a clarification, once removed from the queryParams, it no longer displays in the URL but the `perPage` is still sent to the API.

**Comment by tomaskikutis** [comment]
Why would you want to remove `perPage`, how else should API know which items to return ?

**Comment by ryanwood** [comment]
The API in question is fixed at 30 records per page. Sending the perPage param has no effect on the page size. I would rather remove it than have to either hardcode 30 into the client side or pass another page size that will simply be ignored.   

It simply seems like code smell to see API urls (in the logs or such) with perPage=50 and the result is returning 30 per page.

Honestly, it’s not a huge deal. I can simply ignore it. It would be nice to be able to disable that param from being sent though.

Thanks for a great project!  

- Ryan

**Comment by mharris717** [comment]
My apologies for taking so long to respond here. I'm glad the project is working for you. 

I'm going to close this issue and add a "revisit later" label. I think it's a reasonable feature request, even if it's not critical. I don't want to lose it, but I need to clean up the backlog of open issues I've created with my absence :)

Thanks for taking the time to log the issue in the first place!
