### ISSUE TITLE
Could not find "route-mixin" module

### ISSUE THREAD

**Issue by shunchu** [mharris717/ember-cli-pagination#99]
Has anyone run into this issue with the latest Ember stack?

```javascript
Uncaught Error: Could not find module `ember-cli-pagination/remote/route-mixin` imported from `app-ember/routes/users/index`
```

My Ember stack:

```
Ember: 1.11.0
Ember Data: 1.0.0-beta.16.1
Ember-CLI: 0.2.2
```

This is the code that's experiencing the error:

```coffeescript
# /app-ember/app/routes/users/index.coffee
`import Ember from 'ember'`
`import RouteMixin from 'ember-cli-pagination/remote/route-mixin'`

UsersIndexRoute = Ember.Route.extend(RouteMixin, {
  perPage: 25

  model: (params) ->
    @findPaged('user', params)
})

`export default UsersIndexRoute`
```

It seems like ember-resolver wasn't able to find the module in the route that it's expecting.

**Comment by broerse** [comment]
It is there in my Ember-CLI 0.2.2. I am using the local pagination so I have no code to check the remote for you.  Perhaps remove the node_models folder and run `npm install` again?

**Comment by gte451f** [comment]
I'm using remote pagination on the latest stack with no issue.  The code snippit looks fine as far as I can tell.

**Comment by shunchu** [comment]
After spending some time tracking it down, I found the problem came down to the deprecation of this file in Ember-CLI: `ember-template-compiler.js`.

The error was "sort of" hidden just outside of the view in the console that I missed it (first line even before the Ember-CLI stats).

Adding the following line *above all other* `app.import` statements in `Brocfile.js` resolved it for me:

    app.import('bower_components/ember/ember-template-compiler.js');

Thank you guys for pitching in and responding.
